language: go

env:
- GO111MODULE=on

go:
- 1.13.x

script:
- "make build"
- "make docker-login"
- "make docker-push"
- "curl -sSL https://raw.githubusercontent.com/matousjobanek/api/master/scripts/push-to-quay-nightly.sh | bash -s"