apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: registrationservices.toolchain.dev.openshift.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].reason
    name: Reason
    type: string
  group: toolchain.dev.openshift.com
  names:
    kind: RegistrationService
    listKind: RegistrationServiceList
    plural: registrationservices
    shortNames:
    - rs
    singular: registrationservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RegistrationService is the Schema for the registrationservices
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RegistrationServiceSpec defines the desired state of RegistrationService
          properties:
            authClient:
              description: The AuthClient contains all necessary information about
                the auth client
              properties:
                config:
                  description: The Config contains the auth config
                  type: string
                libraryUrl:
                  description: The LibraryUrl identifies the auth library location
                  type: string
                publicKeysUrl:
                  description: The PublicKeysUrl identifies the public keys location
                  type: string
              type: object
            environment:
              description: The environment identifies which mode the registration
                service should be running in - prod, stage, e2e-tests, dev, etc.
              type: string
            image:
              description: The image identifies which image of the registration service
                should be used for a deployment
              type: string
            replicas:
              description: The number of replicas of the deployed registration service
              type: integer
          required:
          - image
          type: object
        status:
          description: RegistrationServiceStatus defines the observed state of RegistrationService
          properties:
            conditions:
              description: 'Conditions is an array of current Registration Service
                deployment conditions Supported condition reasons: Deploying, and
                Deployed'
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transit from one status to
                      another.
                    format: date-time
                    type: string
                  message:
                    description: Human readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: (brief) reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of condition
                    type: string
                required:
                - status
                - type
                type: object
              type: array
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
