apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: host-operator
  template:
    metadata:
      labels:
        name: host-operator
    spec:
      serviceAccountName: host-operator
      containers:
      - name: host-operator
        # Replace this with the built image name
        image: REPLACE_IMAGE
        command:
        - host-operator
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "host-operator"
        - name: REGISTRATION_SERVICE_IMAGE
          value: REPLACE_REGISTRATION_SERVICE_IMAGE
        - name: REGISTRATION_SERVICE_ENVIRONMENT
          value: REPLACE_REGISTRATION_SERVICE_ENVIRONMENT
        - name: REGISTRATION_SERVICE_AUTH_CLIENT_LIBRARY_URL
          value: REPLACE_REGISTRATION_SERVICE_AUTH_CLIENT_LIBRARY_URL
        - name: REGISTRATION_SERVICE_AUTH_CLIENT_CONFIG_RAW
          value: REPLACE_REGISTRATION_SERVICE_AUTH_CLIENT_CONFIG_RAW
        - name: REGISTRATION_AUTH_CLIENT_PUBLIC_KEYS_URL
          value: REPLACE_REGISTRATION_AUTH_CLIENT_PUBLIC_KEYS_URL
