kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: host-operator
subjects:
- kind: ServiceAccount
  name: host-operator
  namespace: toolchain-host-operator
roleRef:
  kind: ClusterRole
  name: host-operator
  apiGroup: rbac.authorization.k8s.io
