#!/usr/bin/env bash

indentList() {
    local INDENT="      "
    sed -e "s/^/${INDENT}/" \
        -e "1s/^${INDENT}/${INDENT:0:-2}- /"
  }

indentElement() {
    local INDENT="  "
    sed -e "s/^/${INDENT}/"
  }

listCSV() {
  for index in ${!CSV_DIRS[*]}
  do
    cat ${CSV_DIRS[$index]}/*clusterserviceversion.yaml | indentList apiVersion
  done
}

NEXT_CSV_VERSION=0.0.1
CURRENT_CSV_VERSION=0.0.0
PRJ_ROOT_DIR=$(git rev-parse --show-toplevel)
CRDS_DIR=${PRJ_ROOT_DIR}/deploy/crds
PKG_DIR=${PRJ_ROOT_DIR}/deploy/olm-catalog/host-operator
CSV_DIRS[0]=${PKG_DIR}/${NEXT_CSV_VERSION}



operator-sdk olm-catalog gen-csv --csv-version ${NEXT_CSV_VERSION} --from-version ${CURRENT_CSV_VERSION} --update-crds
#sed -i 's/kind: ""/kind: KubeFedCluster/g' ${CSV_DIRS[$index]}/*clusterserviceversion.yaml
#sed -i 's/name: ""/name: kubefedclusters.core.kubefed.io/g' ${CSV_DIRS[$index]}/*clusterserviceversion.yaml
#sed -i 's/version: ""/version: v1beta1\n      description: KubeFedCluster configures kubefed to be aware of a Kubernetes\n        cluster and encapsulates the details necessary to communicate with the cluster..\n      displayName: KubeFedCluster/g' ${CSV_DIRS[$index]}/*clusterserviceversion.yaml
sed -i ':a;N;$!ba;s/  replaces: host-operator.v0.0.0\n//g' ${CSV_DIRS[$index]}/*clusterserviceversion.yaml
sed -i 's|REPLACE_IMAGE|quay.io/matousjobanek/host:alpha|g' ${CSV_DIRS[$index]}/*clusterserviceversion.yaml

NAME=${NAME:-codeready-toolchain-saas-host}
NAMESPACE=${NAMESPACE:-openshift-marketplace}
x=( $(echo $NAME | tr '-' ' ') )
DISPLAYNAME=${DISPLAYNAME:=${x[*]^}}

#CRD=$(cat $(ls $CRDS_DIR/*crd.yaml) | grep -v -- "---" | indentList "apiVersion")

for crd in `ls ./deploy/crds/*crd.yaml`; do cat ${crd} | indentList "apiVersion"; done > /tmp/grouped_crds

PKG=$(cat $(ls $PKG_DIR/*host-operator.package.yaml) | indentList "packageName")

echo "# This file was autogenerated by 'host-operator/olm/olm_catalog.sh'
# Do not edit it manually!
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: $NAME
  namespace: $NAMESPACE
spec:
  configMap: $NAME
  displayName: $DISPLAYNAME
  publisher: Red Hat
  sourceType: internal
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: $NAME
  namespace: $NAMESPACE
data:
  customResourceDefinitions: |-
$(for crd in `ls ./deploy/crds/*crd.yaml`; do cat ${crd} | indentList "apiVersion"; done)
  clusterServiceVersions: |-
$(cat ${CSV_DIRS[$index]}/*clusterserviceversion.yaml | indentList apiVersion)
  packages: |
$PKG" | sed 's/^  *$//' > olm/deploy_csv.yaml